# config/routes.yaml

app_lucky_number:
    path: /
    controller: App\Controller\NumberController::number

find_number:
    path: /find-link
    controller: App\Controller\FindNumberController::FindNumber

change_Lang_Controller:
    path: /change-lang
    controller: App\Controller\ChangeLangController::run

poetry_Controller:
    path: /poetry
    controller: App\Controller\PoetryController::poetry

haiku_Controller:
    path: /haiku
    controller: App\Controller\HaikuController::haiku

story_Controller:
    path: /story
    controller: App\Controller\StoryController::story

begin_book_Controller:
    path: /begin-book
    controller: App\Controller\BeginBookController::book

help_Controller:
    path: /help
    controller: App\Controller\HelpController::help

regulation_Controller:
    path: /link-building-rules
    controller: App\Controller\RegulationController::regulation

go_link:
    path: /__{token}
    controller: App\Controller\GoLinkController::link
    requirements:
      token: .+

open_pdf_list:
    path:  /Mirosław_Mitka-story/{page}
    controller: App\Controller\OpenPdfController::OpenPdf
    condition:  "params['page'] >= 0 && params['page'] <= 3"

open_pdf_list_book:
    path:  /Mirosław_Mitka-book/{page}
    controller: App\Controller\OpenPdfBookController::OpenPdfBook
    condition:  "params['page'] >= 0 && params['page'] <= 0"


