<?php
define('RECPATCHA_PUBLIC_KEY', '6LfjS9keAAAAAP5QiMyIldqDRG_S1igMnDlO5Nwb');
define('RECPATCHA_PRIVATE_KEY', '6LfjS9keAAAAAHTloGPPP-W1dKkodxcwYkJqUcJV'); 

define('RECPATCHA_PUBLIC_KEY_2', '6LcK4ngjAAAAAHE-hEcvdNorPIjQgZBUGZp8Jl_7');
define('RECPATCHA_PRIVATE_KEY_2', '6LcK4ngjAAAAAPfyn0P3CfPFNrm4uGTwP3gxuh2e');